### ISSUE TITLE
before run release_finish.sh

### ISSUE THREAD

**Issue by vTNT** [Voronenko/gitflow-release#1]
after run release_start.sh,  the branch turn to develop branch at last,  but before run release_finish.sh, we need  turn to release branch.
so,  how can i solve this problem?

**Comment by vTNT** [comment]
Whether to add a judgment, if the current branch is not release,  switch to release branch

**Comment by vTNT** [comment]
And if there is more than one release branch locally,  it can notice an error

**Comment by Voronenko** [comment]
Comment is correct. Generally it has to do with question "when semver gets increased".

On pet projects I use case "I release 0.0.1 and start working on 0.0,2"
https://github.com/Voronenko/dotfiles/blob/master/gitflow/release_start.sh  thus  last 5 lines are commented out.

Suggested scenario of repo usage - you fork and adjust for your workflow.
In my workflows only one release branch  is allowed. I.e. release starts, and after some time finishes. We are not working on multiple releases at the time within the same repo.
 
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by vTNT** [comment]
ok, thanks for you share。

**Comment by vTNT** [comment]
For example, our current version is 0.1.1, but we want to develop a new version, so our version number will directly become 1.0.0.  So in the face of this situation, how did you automatically generate version.txt? Is it manual?

**Comment by Voronenko** [comment]
Semversioning:

X.Y.Z

X = breaking changes
Y = major changes, generally compatible
Z = minor patches , saying from hotfixes.

Automatically I increase only Y and Z 

https://github.com/Voronenko/gitflow-release/blob/master/deployment-single-makefile/make_helper.sh#L37

For breaking changes - at some moment I commit new version.txt (usually at a moment when I start branch for refactored application)

**Comment by vTNT** [comment]
thanks for you comment ^-^
